Added base project
saket-capri/prasad-java pull request #1
Opened 2023-08-23 06:50 UTC by PrasadDalweeCapri

POC covered:
1. Functional Programming
2. REST API versioning
3. Custom exception handling
4. Swagger UI
5. Validations

2023-08-23 07:43 UTC, manan-capri requested changes

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/controller/FunctionalProgrammingController.java
> +    private FunctionalProgrammingService service;
change the variable name to meaningful one

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/controller/WebserviceController.java
> +    @GetMapping("/get_all")
change get_all to all

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/controller/WebserviceController.java
> +    @GetMapping("/get_by_id")
change get_by_id to id/{id}

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/controller/WebserviceController.java
> +    public User getByID(@RequestParam int id)
accept id as Path variable instread of Request Param
Also perform null checking

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/controller/WebserviceController.java
> +    @PostMapping("/add_user")
change PostMapping("/add_user") to @PostMapping

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/controller/WebserviceController.java
> +    @DeleteMapping("/delete_by_id")
change @DeleteMapping("/delete_by_id") to @DeleteMapping("{id}")
Also perform null checking

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/controller/WebserviceController.java
> +    public String delete_user(@RequestParam Integer id) {
accept id as Path Variable instead of Request Param

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/util/ListUtils.java
> +    public static boolean evenCheck(int d)
Use Java 8 Predicates to do this operation.

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/util/ListUtils.java
> +    public static Integer getRemainder(int d)
Use Java 8 Predicates to do this operation.

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/service/FunctionalProgrammingService.java
> +    private List<Integer> numbers=List.of(1,2,3,4,5,6,7,8);
since this list is not getting changed anywhere, add final

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/exception/CustomisedExceptionHandler.java
> +public class CustomisedExceptionHandler extends ResponseEntityExceptionHandler
Change the class name to GlobalExceptionHandler

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/exception/CustomisedExceptionHandler.java
> +    @ExceptionHandler(NoSuchElementException.class)
is this exception getting thrown from anywhere?

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/service/UsersDAOService.java
> +    public User addUser(User user)
execute this method's endpoint concurrently and see if it leads to any issues with the value of id variable.If it does then make the id variable volatille.

2023-08-23 07:43 UTC, manan-capri commented on src/main/java/com/rest/webservice/service/FunctionalProgrammingService.java
> +        return x.get();
instead of single value, return a map having key as the number and the value as the output of the remainder operation

2023-08-23 17:23 UTC, saket-capri commented on README.md
what is the need to remove comment in this file ?

2023-08-23 17:23 UTC, saket-capri commented on src/main/java/com/rest/webservice/controller/WebserviceController.java
> +    @GetMapping("/{id}")
:+1:

2023-08-23 17:24 UTC, saket-capri commented on src/main/java/com/rest/webservice/controller/WebserviceController.java
> +    public String putUserData(@PathVariable @NotNull Integer id, @RequestParam String name, @RequestParam LocalDate date)
why are we not using request body to update these parameters ?

2023-08-23 17:24 UTC, saket-capri commented on src/main/java/com/rest/webservice/controller/versioning/VersioningController.java
> +    @GetMapping(value = "/fetch",params ="version=1" )
+1

2023-08-23 17:26 UTC, saket-capri commented
can we add logging ?

2023-08-24 12:22 UTC, manan-capri requested changes

2023-08-24 12:22 UTC, manan-capri commented on src/main/java/com/rest/webservice/service/UsersDAOService.java
> +            throw new NoSuchElementException("No user found");
catch this exception separately and then re-throw it

2023-08-24 12:22 UTC, manan-capri commented on src/main/java/com/rest/webservice/service/UsersDAOService.java
> +            log.error("The requested id:{} doesn't exist",id+e.getMessage());
change + to ,

2023-08-24 12:22 UTC, manan-capri commented on src/main/java/com/rest/webservice/service/UsersDAOService.java
> +            log.info("User Created Successfully: " + users);
why the create log in an update api,also users should not be logged here.

2023-08-24 12:22 UTC, manan-capri commented on src/main/java/com/rest/webservice/service/UsersDAOService.java
> +            log.error("error occurred when updating id:{}",user.getId()+t.getMessage());
change + to ,

2023-08-24 12:27 UTC, manan-capri requested changes

2023-08-24 12:27 UTC, manan-capri commented on src/main/java/com/rest/webservice/controller/versioning/VersioningController.java
> +        if (version.equals(1)) {
what if version is null?

2023-08-25 06:56 UTC, merged