JPA Derived Queries
saket-capri/prasad-java pull request #5
Opened 2023-09-08 06:56 UTC by PrasadDalweeCapri

1. Learned different kinds of supported queries
2. Implemented a controller and a service layer that can utilise almost all of the query types
3. Learned JPA pattern matching for mysql string queries

2023-09-08 07:23 UTC, manan-capri requested changes

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/controller/StudentController.java
> +    public List<Student> filterByDate(@RequestParam @NotNull LocalDate dob, @RequestParam @NotBlank String type) {
add a format validation for date here.

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +                    case "Id" -> studentRepository.findByNameOrderByStudentId(name);
why case for Id, could have used ASC which is also the default type

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +    public List<Student> searchBio(String type, String targetBio) {
use enum for type

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        String type = studentNameDto.type();
use enum for type.

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        String order = studentNameDto.order();
use enum for orderBy

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +                default -> throw new NoSuchElementException();
replace it with throw new ResponseStatusException(
  HttpStatus.NOT_FOUND, "Type not found"
);

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +            result = switch (type) {
create an enum for Active

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +                default -> throw new NoSuchElementException();
replace it with throw new ResponseStatusException(
HttpStatus.NOT_FOUND, "Type not found"
);

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
create an enum for Type

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +                default -> throw new NoSuchElementException();
replace it with throw new ResponseStatusException(
HttpStatus.NOT_FOUND, "Type not found"
);

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
should not return null if data is not found,return 404

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
should not return null if data is not found,return 404

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/controller/StudentController.java
> +    public List<Student> filterByIdCollection(@RequestBody List<Integer> idCollection) {
where is the empty check of list collection

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
what if the default case in both if else also returns no result,should not return null in that case

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
what if default is not executed and the query for any matching case returns no result.

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
what if the table has no records,should not return null

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
what if the table has no records,should not return null or empty list in that case,return 404 custom error

2023-09-08 07:23 UTC, manan-capri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
what if the table has no records,should not return null or empty list in that case,return 404 custom error

2023-09-08 09:06 UTC, PrasadDalweeCapri commented on mysql-webservice/src/main/java/com/rest/webservice/controller/StudentController.java
> +    public List<Student> filterByDate(@RequestParam @NotNull LocalDate dob, @RequestParam @NotBlank String type) {
Done.

2023-09-08 09:13 UTC, PrasadDalweeCapri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +                    case "Id" -> studentRepository.findByNameOrderByStudentId(name);
I just wanted to use all methods available. I will update it to use Asc and Desc as cases and keep orderById as default. It would make more sense that way.

2023-09-08 11:49 UTC, PrasadDalweeCapri commented on mysql-webservice/src/main/java/com/rest/webservice/service/StudentService.java
> +        List<Student> result = null;
I think 204(No Content) makes more sense than 404 (Not Found) in this case

2023-09-11 04:56 UTC, manan-capri approved these changes

2023-09-11 04:56 UTC, merged